[SDK-165] Project Structure and Customization Guide
readyplayerme/rpm-unreal-avatar-creator pull request #14
Opened 2023-06-15 08:45 UTC by gadamyan

## [TICKETID](https://ready-player-me.monday.com/boards/2563815861/pulses/SDK-165)

## Description

-   Added project structure readme
-   Added customization guide readme
-   Refactored the UI

## Changes

#### Added

-   Added project structure readme
-   Added customization guide readme

2023-06-15 10:45 UTC, HarrisonHough requested changes
Mentioned already in Slack but some screenshots would be helpful, making it easier to follow along I think. 
also some minor suggestions in the comments

2023-06-15 10:45 UTC, HarrisonHough commented on CustomizationGuide.md
> +## Constraints
I think ## Requirements would be a better term to use, and maybe you can put it up the top (above Customization Steps). Kinda like we have on other git repos 
![image](https://github.com/readyplayerme/rpm-unreal-avatar-creator/assets/7085672/9432f571-c327-4b13-9c28-ab7f5e76a2a2)

2023-06-15 10:45 UTC, HarrisonHough commented on CustomizationGuide.md
> +You are allowed to change the entire UI, the only thing that you are required to have in your custom implementation is the **Ready Player Me sign-in** button and **Ready Player Me account-creation**
Maybe screenshots of these 2 elements?

2023-06-15 10:45 UTC, HarrisonHough commented on CustomizationGuide.md
> +1. Make sure that you have the `ReadyPlayerMe` and `RpmAvatarCreator` plugins set up for your project.
you could link to the ReadyPlayerMe sdk plugin repo.

2023-06-15 10:45 UTC, HarrisonHough commented on CustomizationGuide.md
> +4. Read the SampleStructure.md readme file to better understand the components of the sample UI.
you could also link to samplestructure.md here

2023-06-15 10:45 UTC, HarrisonHough commented on CustomizationGuide.md
> +3. Open the CHANGELOG.md readme file to check the changes.
link can be added to changlog

2023-06-15 10:45 UTC, HarrisonHough commented on README.md
> +- To add the plugin to your project as a submodule, run the following command in the terminal from your project folder. This is the preferred way of setting up the plugin.
```suggestion
- To add the plugin to your project as a submodule, run the following command in the terminal from your project folder. This is the recommended way to set up the plugin.
```

2023-06-15 12:14 UTC, rYuuk commented
Maybe both the SampleStructure.md and CustomizationGuide.md can be put in a Documentation folder.

2023-06-16 10:48 UTC, gadamyan commented
> Maybe both the SampleStructure.md and CustomizationGuide.md can be put in a Documentation folder.

Moving to Documents folder breaks the links to the files. I don't want to set full path of the files in the readme.

2023-06-20 06:23 UTC, HarrisonHough commented
> > Maybe both the SampleStructure.md and CustomizationGuide.md can be put in a Documentation folder.
> 
> Moving to Documents folder breaks the links to the files. I don't want to set full path of the files in the readme.

It does not break the links you can just update to use relative file paths? 

![image](https://github.com/readyplayerme/rpm-unreal-avatar-creator/assets/7085672/972a2fbc-c758-4183-bc2c-bdf78abc8dcc)

2023-06-20 06:35 UTC, HarrisonHough requested changes
some minor grammatical issues I spotted, feel free to just use the suggestion changes I put there.

2023-06-20 06:35 UTC, HarrisonHough commented on CustomizationGuide.md
> +If you'd like to entirely get rid of the navigation panel, becausee your application already has a navigation panel, these are the steps that you need to do.
typo at beacuase
```suggestion
If you'd like to entirely get rid of the navigation panel, because your application already has a navigation panel, these are the steps that you need to do.
```

2023-06-20 06:35 UTC, HarrisonHough commented on CustomizationGuide.md
> +AvatarCreator Widget uses the navigation panel for the button visibilities and responding the the clicked buttons. You need to replace the navigation panel reference in avatar creator with your own n
Typos
```suggestion
AvatarCreator Widget uses the navigation panel for button visibility and responding to the clicked buttons. You need to replace the navigation panel reference in avatar creator with your own navigation panel. In your own navigation panel add buttons that you need(save, back, ...). Add a blueprint interface NavigationSwitcher to your navigation panel to have a connection with the AvatarCreator. Finally, fix all the blueprint errors connected with the replaced navigation panel.
```

2023-06-20 06:35 UTC, HarrisonHough commented on SampleStructure.md
> +In order for the child widgets to be able to communicate with the avatar creator, they use an interface of the NavigationSwitcher.
```suggestion
In order for the child widgets to be able to communicate with the avatar creator, they use the NavigationSwitcher.
```

2023-06-20 06:35 UTC, HarrisonHough commented on SampleStructure.md
> +The popups widgets are located in the [Popups](Content/Widgets/Popups) folder, they are needed to give the user information of the current sutatus of the avatar creator.
```suggestion
The popups widgets are located in the [Popups](Content/Widgets/Popups) folder, they are needed to give the user information about the current status of the avatar creator.
```

2023-06-20 06:35 UTC, HarrisonHough commented on README.md
> +- To add the plugin to your project as a submodule, run the following command in the terminal from your project folder. This is the preferred way of setting up the plugin.
```suggestion
- To add the plugin to your project as a submodule, run the following command in the terminal from your project folder. This is the recommended way of setting up the plugin.
```

2023-06-20 06:35 UTC, HarrisonHough commented on README.md
> +The plugin is currently in the **alpha** stage. We recommend not using it in production until the stable version is released.
```suggestion
The plugin is currently in **alpha** stage. We do not recommend using it in production until the stable version is released.
```

2023-06-20 08:02 UTC, gadamyan commented
> > > Maybe both the SampleStructure.md and CustomizationGuide.md can be put in a Documentation folder.
> > 
> > 
> > Moving to Documents folder breaks the links to the files. I don't want to set full path of the files in the readme.
> 
> It does not break the links you can just update to use relative file paths?
> 
> ![image](https://user-images.githubusercontent.com/7085672/247023475-972a2fbc-c758-4183-bc2c-bdf78abc8dcc.png)

The relative paths to the documents is not an issue. The relative paths from the documents is an issue. I need to either provide a full path, or `../` for all of the links in the SampleStructure.md document file.

2023-06-20 10:51 UTC, HarrisonHough approved these changes
Looks good now

2023-06-20 13:12 UTC, gadamyan commented
> > > > Maybe both the SampleStructure.md and CustomizationGuide.md can be put in a Documentation folder.
> > > 
> > > 
> > > Moving to Documents folder breaks the links to the files. I don't want to set full path of the files in the readme.
> > 
> > 
> > It does not break the links you can just update to use relative file paths?
> > ![image](https://user-images.githubusercontent.com/7085672/247023475-972a2fbc-c758-4183-bc2c-bdf78abc8dcc.png)
> 
> The relative paths to the documents is not an issue. The relative paths from the documents is an issue. I need to either provide a full path, or `../` for all of the links in the SampleStructure.md document file. Do you think having `../` in front of all the links is OK?

done

2023-06-20 13:14 UTC, merged