[4141296529] Login functionality
readyplayerme/rpm-unreal-avatar-creator pull request #2
Opened 2023-03-20 08:41 UTC by gadamyan

## [4141296529](https://ready-player-me.monday.com/boards/2563815861/pulses/4141296529)

## Description

-   Added LogIn functionality
-   Added LogIn widget
-   Added IBaseRequest interface to be able to make any kind of request.
-   Code refactoring
-   UI fixes for the avatar editor

## Changes

#### Added

-   Added LogIn functionality
-   Added LogIn widget
-   Added IBaseRequest interface to be able to make any kind of request.

#### Updated

-   Code refactoring
-   UI fixes for the avatar editor

## How to Test

-   The functionality  is easily testable in the Example Project

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

2023-03-20 11:38 UTC, HarrisonHough requested changes
Some small change suggestions in comments

2023-03-20 11:38 UTC, HarrisonHough commented on Source/RpmAvatarCreator/Private/Extractors/UserDataExtractor.cpp
> +	if (!FJsonSerializer::Deserialize(Reader, JsonObject) || !JsonObject->HasField("data"))
this "data" field is used in a lot of places. Maybe move it to a constant, if it ever changed it would currently need to be changed in lots of different places

2023-03-20 11:38 UTC, HarrisonHough commented on Source/RpmAvatarCreator/Private/Extractors/UserDataExtractor.cpp
> +	if (!DataObject->HasField("refreshToken") || !DataObject->HasField("token"))
same thing here with token and refresh token, no need to hard code the things in multiple places.

2023-03-20 11:46 UTC, HarrisonHough commented
Might just be a setup issue or something but the quality of the eye textures is bad, very pixelated 
![image](https://user-images.githubusercontent.com/7085672/226329182-1059098a-3f1c-44ce-80a4-2d25f063d5d9.png)

Sometimes when I run the demo scene I get all these errors? 
![image](https://user-images.githubusercontent.com/7085672/226329560-51d29280-be28-425b-b739-a1e45ede869a.png)

Minor thing but I think the demo map for creator should have a more descriptive name EG AvatarCreatorDemo 
At the moment if you want to find/add it to default maps it's difficult to tell which one it is. 
![image](https://user-images.githubusercontent.com/7085672/226329927-3d93bae1-34ff-4a11-8df4-1b6eaf7ed20f.png)


Not sure if bug or just missing feature but initial glasses (no glasses) option should be selected when avatar first loads
![image](https://user-images.githubusercontent.com/7085672/226330212-461a0d91-0b63-4982-91ab-6f9d0f4df146.png)

2023-03-21 15:55 UTC, gadamyan commented on Source/RpmAvatarCreator/Private/Extractors/UserDataExtractor.cpp
> +	if (!DataObject->HasField("refreshToken") || !DataObject->HasField("token"))
Done. I'll do some refactoring when the AvatarCreator is ready. I'll refactor all the extractors

2023-03-22 12:15 UTC, gadamyan commented
> We will need an ability to if a user with account or anonymously logged in before, and the ability to log out. Atm it keeps using the same settings.

Done, but it isn't perfect. The UE doesn't have a dropdown component. I created a custom one and toggled the visibility when clicking on the UserProfile.

2023-03-22 12:17 UTC, gadamyan commented
> Might just be a setup issue or something but the quality of the eye textures is bad, very pixelated ![image](https://user-images.githubusercontent.com/7085672/226329182-1059098a-3f1c-44ce-80a4-2d25f063d5d9.png)
> 
> Sometimes when I run the demo scene I get all these errors? ![image](https://user-images.githubusercontent.com/7085672/226329560-51d29280-be28-425b-b739-a1e45ede869a.png)
> 
> Minor thing but I think the demo map for creator should have a more descriptive name EG AvatarCreatorDemo At the moment if you want to find/add it to default maps it's difficult to tell which one it is. ![image](https://user-images.githubusercontent.com/7085672/226329927-3d93bae1-34ff-4a11-8df4-1b6eaf7ed20f.png)
> 
> Not sure if bug or just missing feature but initial glasses (no glasses) option should be selected when avatar first loads ![image](https://user-images.githubusercontent.com/7085672/226330212-461a0d91-0b63-4982-91ab-6f9d0f4df146.png)

Except for the Eye Color everything is done.
Blure issue is a known issue in UE, several UE devs were complaining about it, but I didn't find any solution for it.

2023-03-23 08:38 UTC, HarrisonHough approved these changes
Looks good and seems to work. 
One minor unrelated thing but for the Avatar Creator demo map the X (close) button is kinda pointless as you can't get the window to display again after you close it. 

![image](https://user-images.githubusercontent.com/7085672/227147887-b2a1397f-b467-4806-9eed-c80c4db0a970.png)

2023-03-24 22:33 UTC, merged

2023-03-30 10:07 UTC, gadamyan commented
> Looks good and seems to work. One minor unrelated thing but for the Avatar Creator demo map the X (close) button is kinda pointless as you can't get the window to display again after you close it.
> 
> ![image](https://user-images.githubusercontent.com/7085672/227147887-b2a1397f-b467-4806-9eed-c80c4db0a970.png)

Will do in the next pr